#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: bulletscreen
#        uri: lb://bullet
#        predicates:
#        - Path=/bullet/info/**
#      - id: bulletscreen
#        uri: lb:ws://bullet
#        predicates:
#        - Path=/bullet/**
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:8081
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
      - id: host_route
        uri: http://localhost:8082
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1

#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/incaseoffailureusethis
#        - RewritePath=/consumingserviceendpoint, /backingserviceendpoint
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    ROOT: DEBUG
  instance:
    instanceId: ${spring.application.name):${random.int}
  file: D:\logs\${spring.application.name}-${server.port}.log