spring:
  cloud:
    gateway:
      routes:
#      - id: bulletscreen
##        uri: lb://bullet
#        uri: lb://http://localhost:8764/bullet
#        predicates:
#        - Path=/bullet/info/**
#        - Weight=WEBSOCKET,5
#      - id: bulletscreen1
##        uri: lb:ws://bullet
#        uri: lb:ws://localhost:8764/bullet
#        predicates:
#        - Path=/bullet/**
#        - Weight=WEBSOCKET,5
      - id: wsvice
        uri: lb:ws://WEBSOCKET/websocket
#        uri: lb://websocket
        predicates:
        - Path=/websocket/**
        - Weight=WEBSOCKET,5

server:
  port: 8888
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    ROOT: INFO
  instance:
    instanceId: ${spring.application.name):${random.int}
  file: D:\logs\${spring.application.name}-${server.port}.log